{% set version = '0.4-93' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-circular
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://cran.r-project.org/src/contrib/circular_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/circular/circular_{{ version }}.tar.gz
  sha256: 76cee2393757390ad91d3db3e5aeb2c2d34c0a46822b7941498571a473417142

build:
  merge_build_host: True  # [win]
  number: 1003
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-boot
    - r-mvtnorm
  run:
    - r-base
    - r-boot
    - r-mvtnorm

test:
  commands:
    - $R -e "library('circular')"  # [not win]
    - "\"%R%\" -e \"library('circular')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=circular
  license: GPL-2
  summary: Circular Statistics, from "Topics in circular Statistics" (2001) S. Rao Jammalamadaka
    and A. SenGupta, World Scientific.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
