# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangfortran_compilergfortran
    - CONFIG=osx_c_compilertoolchain_cfortran_compilertoolchain_fort

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "T6ZIyZ9mr+U8i36palFOiLGIbtSmBNwKFmDZ527tJiLtH3r6R472y5hFwOeERKzGKvd5kpZnVZN/2MFbmJTDS10+HYPH/0MTyrXooHpUc+9p1kXS/oAhq8hHOmq6agtdkg1M9cimal1Kl1yxr/CmfcOw66+4eisYj0FXVbyYqtF3omZuY5/AzeEOTYz7V4mLf9ZBfoNpdHbvmPvO1oW/KNfzMYQeWdUF3RAKkWsAw+H9+IsfuyZVs6vHPg1t3By4RmyLAafJ6DvMxBHPCt+jY5nIRE5I6JuKxY83iCJoqnptyJhMGp1wEviPoVAhyOrbcCrdHa+0fyDX3wnsbsPH0oGXqPflsheh+K4puGnnTLQJeKZQpBfAR7eAeS/NffRGgqm4pFQfGPDwcOTbFDKiBW7ae8G2BG1u1Nr2K4sty+CW1j8bGAjD9W81PzH4QD79SuwbgFU3brmeWCTDySQ2vUDc3UJcj8nfFBS2cCHajG3ccIX3ChgWc3rfBwM68iUsgTrP6LeEdCpek7HDQ29FllJ4/tkpwK497bza3GK8bvTLGrmdjihMsJAP+VdqJ/UcZL/+v0og+skYT+xbuk6sTtGK5yOm2xp+ltMIT1Mfmoa6Qe+M6FhjekJh7PPK6p47KZ8G1rnsOEuRE92RvqscFV+xTORZqXS7vUFDmTnxQqw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
