travis:
  secure:
    BINSTAR_TOKEN: T6ZIyZ9mr+U8i36palFOiLGIbtSmBNwKFmDZ527tJiLtH3r6R472y5hFwOeERKzGKvd5kpZnVZN/2MFbmJTDS10+HYPH/0MTyrXooHpUc+9p1kXS/oAhq8hHOmq6agtdkg1M9cimal1Kl1yxr/CmfcOw66+4eisYj0FXVbyYqtF3omZuY5/AzeEOTYz7V4mLf9ZBfoNpdHbvmPvO1oW/KNfzMYQeWdUF3RAKkWsAw+H9+IsfuyZVs6vHPg1t3By4RmyLAafJ6DvMxBHPCt+jY5nIRE5I6JuKxY83iCJoqnptyJhMGp1wEviPoVAhyOrbcCrdHa+0fyDX3wnsbsPH0oGXqPflsheh+K4puGnnTLQJeKZQpBfAR7eAeS/NffRGgqm4pFQfGPDwcOTbFDKiBW7ae8G2BG1u1Nr2K4sty+CW1j8bGAjD9W81PzH4QD79SuwbgFU3brmeWCTDySQ2vUDc3UJcj8nfFBS2cCHajG3ccIX3ChgWc3rfBwM68iUsgTrP6LeEdCpek7HDQ29FllJ4/tkpwK497bza3GK8bvTLGrmdjihMsJAP+VdqJ/UcZL/+v0og+skYT+xbuk6sTtGK5yOm2xp+ltMIT1Mfmoa6Qe+M6FhjekJh7PPK6p47KZ8G1rnsOEuRE92RvqscFV+xTORZqXS7vUFDmTnxQqw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
